blank_issues_enabled: false
contact_links:
  - name: "FabricTools Community"
    url: https://github.com/dataplat/FabricTools/discussions
    about: "To talk to the community and maintainers of FabricTools, please head to GitHub discussions."
