name: New function proposal
description: If you have a new function proposal that you think should be added to this module.
title: "NewFunctionName: New resource proposal"
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please replace `NewFunctionName` in the issue title (above) with your proposed function name.

        Thank you for contributing and making FabricTools better!
  - type: textarea
    id: description
    attributes:
      label: Function proposal
      description: Provide information how this function will/should work and how it will help users.
    validations:
      required: true
  - type: textarea
    id: proposedProperties
    attributes:
      label: Proposed properties
      description: |
        List all the proposed properties and parameters that the function should have.
      value: |
        Parameter | Description | Data type | Default value | Allowed values
        --- | --- | --- | --- | ---
        ParameterName | Detailed description | String | None | Any

        Property | Description
        --- | ---
        PropertyName | Detailed description
    validations:
      required: true
  - type: textarea
    id: considerations
    attributes:
      label: Special considerations or limitations
      description: |
        Provide any considerations or limitations you can think of that a contributor should take in account when coding the proposed function, and or what limitations a user will encounter or should consider when using the proposed function.
    validations:
      required: true
