<#
.SYNOPSIS
    Generates README.md for the tests/Integration folder listing all functions
    covered by integration tests.

.DESCRIPTION
    Scans every *.Tests.ps1 file in the same directory as this script,
    extracts:
      - The Describe block title (used as the test suite name)
      - The Context block titles (used as scenario names)
      - All FabricTools function calls (*-Fabric* pattern)
    Then writes a README.md with a coverage table grouped by test file.

.EXAMPLE
    # From repo root
    pwsh -File tests/Integration/New-IntegrationReadme.ps1
#>

[CmdletBinding()]
param (
    [Parameter()]
    [string]$OutputPath = (Join-Path $PSScriptRoot "README.md")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# 1. Collect all integration test files in the same directory as this script
# ---------------------------------------------------------------------------
$testFiles = @(Get-ChildItem -Path $PSScriptRoot -Filter "*.Tests.ps1" -File |
    Sort-Object Name)

if ($testFiles.Count -eq 0) {
    Write-Warning "No *.Tests.ps1 files found in '$PSScriptRoot'. README not generated."
    return
}

# ---------------------------------------------------------------------------
# 2. Parse each test file
# ---------------------------------------------------------------------------
$suites = foreach ($file in $testFiles) {
    $content = Get-Content -Path $file.FullName -Raw

    # Extract Describe title (first one wins)
    $describeTitle = if ($content -match 'Describe\s+"([^"]+)"') { $Matches[1] } else { $file.BaseName }

    # Extract all Context titles in order
    $contexts = [regex]::Matches($content, 'Context\s+"([^"]+)"') |
        ForEach-Object { $_.Groups[1].Value }

    # Extract unique FabricTools function calls (*-Fabric*)
    $functions = [regex]::Matches($content, '\b([A-Z][a-zA-Z]+-Fabric[A-Za-z]+)\b') |
        ForEach-Object { $_.Groups[1].Value } |
        Where-Object { $_ -notmatch '^(Mock|Should|Invoke)' } |
        Sort-Object -Unique

    [PSCustomObject]@{
        File      = $file.Name
        Suite     = $describeTitle
        Contexts  = $contexts
        Functions = $functions
    }
}

# ---------------------------------------------------------------------------
# 3. Build README content
# ---------------------------------------------------------------------------
$lines = [System.Collections.Generic.List[string]]::new()

$lines.Add("# Integration Tests")
$lines.Add("")
$lines.Add("This folder contains end-to-end integration tests that call the live Fabric REST API.")
$lines.Add("No mocking is used — a valid authenticated session is required before running.")
$lines.Add("")
$lines.Add("## Prerequisites")
$lines.Add("")
$lines.Add('```powershell')
$lines.Add("Connect-FabricAccount")
$lines.Add('```')
$lines.Add("")
$lines.Add("## Running the tests")
$lines.Add("")
$lines.Add('```powershell')
$lines.Add('Invoke-Pester -Path "tests/Integration/" -Tag "Integration" -Output Detailed')
$lines.Add('```')
$lines.Add("")
$lines.Add("---")
$lines.Add("")
$lines.Add("## Coverage")
$lines.Add("")

foreach ($suite in $suites) {
    $lines.Add("### $($suite.Suite)")
    $lines.Add("")
    $lines.Add("**File:** ``$($suite.File)``")
    $lines.Add("")

    if ($suite.Contexts.Count -gt 0) {
        $lines.Add('**Scenarios:**')
        $lines.Add("")
        foreach ($ctx in $suite.Contexts) {
            $lines.Add("- $ctx")
        }
        $lines.Add("")
    }

    if ($suite.Functions.Count -gt 0) {
        $lines.Add('**Functions covered:**')
        $lines.Add("")
        $lines.Add("| Function | Module Area |")
        $lines.Add("|----------|-------------|")
        foreach ($fn in $suite.Functions) {
            # Derive area from the noun portion after "Fabric"
            $noun = if ($fn -match '-Fabric(.+)$') { $Matches[1] } else { $fn }
            $area = switch -Regex ($noun) {
                '^Workspace' { 'Workspace' }
                '^Capacity'  { 'Capacity'  }
                '^Domain'    { 'Domain'    }
                '^Item'      { 'Item'      }
                '^Lakehouse' { 'Lakehouse' }
                '^Notebook'  { 'Notebook'  }
                '^Pipeline'  { 'Pipeline'  }
                '^Spark'     { 'Spark'     }
                default      { 'General'   }
            }
            $lines.Add("| ``$fn`` | $area |")
        }
        $lines.Add("")
    }

    $lines.Add("---")
    $lines.Add("")
}

# All unique functions across all suites
$allFunctions = $suites | ForEach-Object { $_.Functions } | Sort-Object -Unique

$lines.Add("## All covered functions ($($allFunctions.Count))")
$lines.Add("")
foreach ($fn in $allFunctions) {
    $lines.Add("- ``$fn``")
}
$lines.Add("")
$lines.Add("*Generated by ``New-IntegrationReadme.ps1`` on $(Get-Date -Format 'yyyy-MM-dd HH:mm')*")

# ---------------------------------------------------------------------------
# 4. Write the file
# ---------------------------------------------------------------------------
$lines | Set-Content -Path $OutputPath -Encoding UTF8
Write-Host "README written to: $OutputPath"

Get-Error
