#
# Module manifest for module 'FabricTools'
#
# Generated by: Ioana Bouariu
#
# Generated on: 05.11.2023
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'FabricTools.psm1'

    # Version number of this module.
    ModuleVersion     = '0.20.0'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID              = 'f2a0f9e6-fab6-41fc-9e1c-0c94ff38f794'

    # Author of this module
    Author            = 'The FabricTools Team'

    # Company or vendor of this module
    CompanyName       = 'fabrictools.io'

    # Copyright statement for this module
    Copyright         = 'Copyright (c) 2025 by FabricTools, licensed under MIT'

    # Description of the functionality provided by this module
    Description       = 'A module to be able to do more with Microsoft Fabric.
    It lets you pause and resume Fabric capacities.
    Adds functionallity previously only available with the REST API as PowerShell functions.
    There are also functions to make it easier to monitor usage metrics and refreshes.
    It also adds Fabric-friendly aliases for PowerBI functions to make it easier to use the module.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @('Az.Accounts', 'Az.Resources','MicrosoftPowerBIMgmt')

    # Assemblies that must be loaded prior to importing this module
    #RequiredAssemblies = @('Microsoft.Azure.PowerShell.Authentication')

    # Script files () that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules     = ''

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        "Add-FabricWorkspaceIdentity",
        "Add-FabricWorkspaceRoleAssignment",
        "Assign-FabricDomainWorkspaceByCapacity",
        "Assign-FabricDomainWorkspaceById",
        "Assign-FabricDomainWorkspaceByPrincipal",
        "Assign-FabricDomainWorkspaceRoleAssignment",
        "Assign-FabricWorkspaceCapacity",
        "Confirm-FabricAuthToken",
        "Connect-FabricAccount",
        "Convert-FromBase64",
        "Convert-ToBase64",
        "Export-FabricItem",
        "Get-AllFabricCapacities",
        "Get-AllFabricDatasetRefreshes",
        "Get-FabricAPIClusterURI",
        "Get-FabricAuthToken",
        "Get-FabricCapacity",
        "Get-FabricCapacityRefreshables",
        "Get-FabricCapacitySkus",
        "Get-FabricCapacityState",
        "Get-FabricCapacityTenantOverrides",
        "Get-FabricCapacityTenantSettingOverrides",
        "Get-FabricCapacityWorkload",
        "Get-FabricConnection",
        "Get-FabricCopyJob",
        "Get-FabricCopyJobDefinition",
        "Get-FabricDashboard",
        "Get-FabricDatamart",
        "Get-FabricDataPipeline",
        "Get-FabricDatasetRefreshes",
        "Get-FabricDebugInfo",
        "Get-FabricDomain",
        "Get-FabricDomainTenantSettingOverrides",
        "Get-FabricDomainWorkspace",
        "Get-FabricEnvironment",
        "Get-FabricEnvironmentLibrary",
        "Get-FabricEnvironmentSparkCompute",
        "Get-FabricEnvironmentStagingLibrary",
        "Get-FabricEnvironmentStagingSparkCompute",
        "Get-FabricEventhouse",
        "Get-FabricEventhouseDefinition",
        "Get-FabricEventstream",
        "Get-FabricEventstreamDefinition",
        "Get-FabricExternalDataShares",
        "Get-FabricItem",
        "Get-FabricKQLDashboard",
        "Get-FabricKQLDashboardDefinition",
        "Get-FabricKQLDatabase",
        "Get-FabricKQLDatabaseDefinition",
        "Get-FabricKQLQueryset",
        "Get-FabricKQLQuerysetDefinition",
        "Get-FabricLakehouse",
        "Get-FabricLakehouseTable",
        "Get-FabricLongRunningOperation",
        "Get-FabricLongRunningOperationResult",
        "Get-FabricMirroredDatabase",
        "Get-FabricMirroredDatabaseDefinition",
        "Get-FabricMirroredDatabaseStatus",
        "Get-FabricMirroredDatabaseTableStatus",
        "Get-FabricMirroredWarehouse",
        "Get-FabricMLExperiment",
        "Get-FabricMLModel",
        "Get-FabricNotebook",
        "Get-FabricNotebookDefinition",
        "Get-FabricPaginatedReport",
        "Get-FabricReflex",
        "Get-FabricReflexDefinition",
        "Get-FabricReport",
        "Get-FabricReportDefinition",
        "Get-FabricSemanticModel",
        "Get-FabricSemanticModelDefinition",
        "Get-FabricSparkCustomPool",
        "Get-FabricSparkJobDefinition",
        "Get-FabricSparkJobDefinitionDefinition",
        "Get-FabricSparkSettings",
        "Get-FabricSQLDatabase",
        "Get-FabricSQLEndpoint",
        "Get-FabricTenantSetting",
        "Get-FabricTenantSettings",
        "Get-FabricUsageMetricsQuery",
        "Get-FabricUserListAccessEntities",
        "Get-FabricWarehouse",
        "Get-FabricWorkspace",
        "Get-FabricWorkspaceDatasetRefreshes",
        "Get-FabricWorkspaceRoleAssignment",
        "Get-FabricWorkspaceTenantSettingOverrides",
        "Get-FabricWorkspaceUsageMetricsData",
        "Get-FabricWorkspaceUsers",
        "Get-SHA256",
        "Import-FabricItem",
        "Invoke-FabricAPIRequest",
        "Invoke-FabricAPIRequest",
        "Invoke-FabricDatasetRefresh",
        "Invoke-FabricKQLCommand",
        "Load-FabricLakehouseTable",
        "New-FabricCopyJob",
        "New-FabricDataPipeline",
        "New-FabricDomain",
        "New-FabricEnvironment",
        "New-FabricEventhouse",
        "New-FabricEventstream",
        "New-FabricKQLDashboard",
        "New-FabricKQLDatabase",
        "New-FabricKQLQueryset",
        "New-FabricLakehouse",
        "New-FabricMirroredDatabase",
        "New-FabricMLExperiment",
        "New-FabricMLModel",
        "New-FabricNotebook",
        "New-FabricNotebookNEW",
        "New-FabricReflex",
        "New-FabricReport",
        "New-FabricSemanticModel",
        "New-FabricSparkCustomPool",
        "New-FabricSparkJobDefinition",
        "New-FabricSQLDatabase",
        "New-FabricWarehouse",
        "New-FabricWorkspace",
        "New-FabricWorkspaceUsageMetricsReport",
        "Publish-FabricEnvironment",
        "Register-FabricWorkspaceToCapacity",
        "Remove-FabricCopyJob",
        "Remove-FabricDataPipeline",
        "Remove-FabricDomain",
        "Remove-FabricEnvironment",
        "Remove-FabricEnvironmentStagingLibrary",
        "Remove-FabricEventhouse",
        "Remove-FabricEventstream",
        "Remove-FabricItem",
        "Remove-FabricKQLDashboard",
        "Remove-FabricKQLDatabase",
        "Remove-FabricKQLQueryset",
        "Remove-FabricLakehouse",
        "Remove-FabricMirroredDatabase",
        "Remove-FabricMLExperiment",
        "Remove-FabricMLModel",
        "Remove-FabricNotebook",
        "Remove-FabricReflex",
        "Remove-FabricReport",
        "Remove-FabricSemanticModel",
        "Remove-FabricSparkCustomPool",
        "Remove-FabricSparkJobDefinition",
        "Remove-FabricSQLDatabase",
        "Remove-FabricWarehouse",
        "Remove-FabricWorkspace",
        "Remove-FabricWorkspaceIdentity",
        "Remove-FabricWorkspaceRoleAssignment",
        "Resume-FabricCapacity",
        "Revoke-FabricCapacityTenantSettingOverrides",
        "Revoke-FabricExternalDataShares",
        "Set-FabricApiHeaders",
        "Set-FabricAuthToken",
        "Start-FabricLakehouseTableMaintenance",
        "Start-FabricMirroredDatabaseMirroring",
        "Start-FabricSparkJobDefinitionOnDemand",
        "Stop-FabricEnvironmentPublish",
        "Stop-FabricMirroredDatabaseMirroring",
        "Suspend-FabricCapacity",
        "Test-FabricApiResponse",
        "Unassign-FabricDomainWorkspace",
        "Unassign-FabricDomainWorkspaceRoleAssignment",
        "Unassign-FabricWorkspaceCapacity",
        "Unregister-FabricWorkspaceToCapacity",
        "Update-FabricCapacityTenantSettingOverrides",
        "Update-FabricCopyJob",
        "Update-FabricCopyJobDefinition",
        "Update-FabricDataPipeline",
        "Update-FabricDomain",
        "Update-FabricEnvironment",
        "Update-FabricEnvironmentStagingSparkCompute",
        "Update-FabricEventhouse",
        "Update-FabricEventhouseDefinition",
        "Update-FabricEventstream",
        "Update-FabricEventstreamDefinition",
        "Update-FabricKQLDashboard",
        "Update-FabricKQLDashboardDefinition",
        "Update-FabricKQLDatabase",
        "Update-FabricKQLDatabaseDefinition",
        "Update-FabricKQLQueryset",
        "Update-FabricKQLQuerysetDefinition",
        "Update-FabricLakehouse",
        "Update-FabricMirroredDatabase",
        "Update-FabricMirroredDatabaseDefinition",
        "Update-FabricMLExperiment",
        "Update-FabricMLModel",
        "Update-FabricNotebook",
        "Update-FabricNotebookDefinition",
        "Update-FabricPaginatedReport",
        "Update-FabricReflex",
        "Update-FabricReflexDefinition",
        "Update-FabricReport",
        "Update-FabricReportDefinition",
        "Update-FabricSemanticModel",
        "Update-FabricSemanticModelDefinition",
        "Update-FabricSparkCustomPool",
        "Update-FabricSparkJobDefinition",
        "Update-FabricSparkJobDefinitionDefinition",
        "Update-FabricSparkSettings",
        "Update-FabricTenantSetting",
        "Update-FabricWarehouse",
        "Update-FabricWorkspace",
        "Update-FabricWorkspaceRoleAssignment",
        "Upload-FabricEnvironmentStagingLibrary"
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @(
    "Export-FabItem",
    "Get-FabricDataset",
    "Get-FabricReport",
    "Login-Fabric",
    "Logout-Fabric"
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags         = @("microsoftfabric", "powerbi", "developermode", "pbip", "FabricTools", "Fabric")

            # A URL to the license for this module.
            LicenseUri   = 'https://www.github.com/dataplat/FabricTools/LICENSE.md'

            # A URL to the main website for this project.
            ProjectUri   = 'https://www.github.com/dataplat/FabricTools'

            # A URL to an icon representing this module.
            IconUri      = 'https://raw.githubusercontent.com/dataplat/FabricTools/main/images/FabricToolsLogo.ico'

            # ReleaseNotes of this module
            ReleaseNotes = 'https://github.com/dataplat/FabricTools/blob/main/ReleaseNotes.md'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI = 'https://www.github.com/dataplat/FabricTools'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

